"""Domain contracts for Agent Team.

This package is the forward-facing domain boundary for Team contracts.
"""

from .models import (
    ApprovalState,
    BackendEnvironment,
    BackendHandle,
    BackendSelection,
    BatchRecord,
    BatchState,
    DeliveryReceipt,
    EventFailure,
    EventRecipientType,
    IntegrationReport,
    LeadLease,
    MemberBackend,
    MemberLaunchSpec,
    MemberRecord,
    MemberSpec,
    MemberState,
    MessageProtocol,
    ResolvedBackend,
    RoleEventCursor,
    TaskKind,
    TaskPatch,
    TaskResult,
    TeamError,
    TeamEvent,
    TeamEventState,
    TeamMessage,
    TeamRecord,
    TeamSnapshot,
    TeamState,
    TeamTask,
    TeamTaskState,
    WakeEndpoint,
)
from .roles import LEAD_ROLE_NAME

__all__ = [
    "ApprovalState",
    "BackendEnvironment",
    "BackendHandle",
    "BackendSelection",
    "BatchRecord",
    "BatchState",
    "DeliveryReceipt",
    "EventFailure",
    "EventRecipientType",
    "IntegrationReport",
    "LEAD_ROLE_NAME",
    "LeadLease",
    "MemberBackend",
    "MemberLaunchSpec",
    "MemberRecord",
    "MemberSpec",
    "MemberState",
    "MessageProtocol",
    "ResolvedBackend",
    "RoleEventCursor",
    "TaskKind",
    "TaskPatch",
    "TaskResult",
    "TeamError",
    "TeamEvent",
    "TeamEventState",
    "TeamMessage",
    "TeamRecord",
    "TeamSnapshot",
    "TeamState",
    "TeamTask",
    "TeamTaskState",
    "WakeEndpoint",
]
